# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7076893139b11ecfed0b9bb7bde4f5e"
name = "own-calculator"
handle = "own-calculator"
application_url = "https://assessments-stretch-fears-appraisal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "new-test-store-data.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_cart_transforms,write_cart_transforms,write_products"

[auth]
redirect_urls = [
  "https://assessments-stretch-fears-appraisal.trycloudflare.com/auth/callback",
  "https://assessments-stretch-fears-appraisal.trycloudflare.com/auth/shopify/callback",
  "https://assessments-stretch-fears-appraisal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
